# Don't print a new line at the start of the prompt
add_newline = false

command_timeout=5000

[directory]
truncation_length = 3
format = "[$path]($style)[$lock_symbol]($lock_style) "

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ–](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

#[username]
#style_user = "bold dimmed blue"
#show_always = true

[line_break]
disabled = true

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[[battery.display]]
threshold = 30
style = "bold red"

[java]
disabled = true

[python]
disabled = true
